import {
  User,
  Property,
  Tenant,
  RentPayment,
  Lease,
  MaintenanceRequest,
  RoommateProfile,
  NotificationItem,
  RentalApplication,
} from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'user_landlord_1',
    name: 'Tendai Mutasa',
    email: 'tendai.mutasa@comfort.co.zw',
    phone: '+263 77 212 3456',
    role: 'landlord',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    verified: true,
    city: 'Harare',
    bio: 'Individual property owner managing modern flats & cottages in Avondale and Belvedere with solar & borehole.',
    createdAt: Date.now() - 60 * 86400000,
  },
  {
    id: 'user_tenant_1',
    name: 'Ruvimbo Chitepo',
    email: 'ruvimbo.chitepo@gmail.com',
    phone: '+263 71 987 6543',
    role: 'tenant',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    verified: true,
    city: 'Harare',
    bio: 'Junior Software Engineer at local fintech, looking for quiet accommodation near CBD or Avenues.',
    createdAt: Date.now() - 30 * 86400000,
  },
  {
    id: 'user_manager_1',
    name: 'Farai Ncube (Premier Estates)',
    email: 'farai@premierestates.co.zw',
    phone: '+263 78 345 6789',
    role: 'property_manager',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    verified: true,
    city: 'Bulawayo',
    bio: 'Managing 25+ residential units and student complexes across Harare and Bulawayo.',
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: 'user_admin_1',
    name: 'Comfort Admin',
    email: 'admin@comforthub.co.zw',
    phone: '+263 77 000 1122',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    verified: true,
    city: 'Harare',
    bio: 'Comfort Housing Platform Operations & Moderation Team.',
    createdAt: Date.now() - 120 * 86400000,
  },
];

export const SEED_PROPERTIES: Property[] = [
  {
    id: 'prop_harare_avondale_cottage',
    landlordId: 'user_landlord_1',
    landlordName: 'Tendai Mutasa',
    landlordPhone: '+263 77 212 3456',
    landlordEmail: 'tendai.mutasa@comfort.co.zw',
    name: 'Modern 2-Bed Cottage with Solar & Borehole',
    propertyType: 'Cottage',
    rentUsd: 380,
    rentZig: 10450,
    depositUsd: 380,
    province: 'Harare',
    city: 'Harare',
    suburb: 'Avondale',
    address: '14 Cambridge Road, Avondale',
    bedrooms: 2,
    bathrooms: 1,
    photos: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80',
    ],
    amenities: [
      'Solar Power',
      'Borehole Water',
      'WiFi',
      'Prepaid ZESA',
      'Water Tank',
      'Walled & Gated',
      'Parking',
      '24/7 Security',
    ],
    description:
      'Charming, self-contained 2-bedroom garden cottage in the heart of Avondale. Features uninterrupted 5kVA solar backup, prolific borehole water connected to 5000L Jojo tank with booster pump, separate prepaid ZESA meter, fast fiber WiFi, and paved parking bay. Close to Avondale Shopping Centre.',
    availability: 'Immediate',
    gpsLat: -17.795,
    gpsLng: 31.038,
    featured: true,
    views: 342,
    createdAt: Date.now() - 14 * 86400000,
    updatedAt: Date.now() - 2 * 86400000,
  },
  {
    id: 'prop_harare_avenues_flat',
    landlordId: 'user_landlord_1',
    landlordName: 'Tendai Mutasa',
    landlordPhone: '+263 77 212 3456',
    name: 'Renovated 1-Bed Avenues Apartment (Solar & Council Tank)',
    propertyType: 'Apartment',
    rentUsd: 260,
    rentZig: 7150,
    depositUsd: 260,
    province: 'Harare',
    city: 'Harare',
    suburb: 'Avenues',
    address: 'Corner 6th Street & Josiah Chinamano Ave, Avenues',
    bedrooms: 1,
    bathrooms: 1,
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
    ],
    amenities: [
      'Solar Power',
      'Water Tank',
      'Prepaid ZESA',
      'Walled & Gated',
      'Parking',
      'Furnished',
    ],
    description:
      'Neat, secure 1-bedroom flat in well-maintained block with working elevator, solar lighting in common areas, dedicated backup water reservoir, modern fitted granite kitchen, and built-in cupboards. Ideal for young professional or CBD worker.',
    availability: 'Immediate',
    gpsLat: -17.822,
    gpsLng: 31.053,
    featured: true,
    views: 520,
    createdAt: Date.now() - 21 * 86400000,
    updatedAt: Date.now() - 5 * 86400000,
  },
  {
    id: 'prop_harare_mt_pleasant_student',
    landlordId: 'user_manager_1',
    landlordName: 'Farai Ncube (Premier Estates)',
    landlordPhone: '+263 78 345 6789',
    name: 'Executive Student Boarding House (Walking Distance to UZ)',
    propertyType: 'Student Accommodation',
    rentUsd: 110,
    rentZig: 3025,
    depositUsd: 50,
    province: 'Harare',
    city: 'Harare',
    suburb: 'Mount Pleasant',
    address: 'Pendennis Road, Mount Pleasant',
    bedrooms: 1,
    bathrooms: 2,
    photos: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800&auto=format&fit=crop&q=80',
    ],
    amenities: [
      'Solar Power',
      'Borehole Water',
      'WiFi',
      'Furnished',
      '24/7 Security',
      'Water Tank',
    ],
    description:
      'Comfortable student accommodation 8 minutes walk to University of Zimbabwe (UZ) main campus. Rate includes high-speed uncapped Wi-Fi, 24/7 solar study power, borehole water, study desk, single bed with orthopedic mattress, shared modern kitchen, and full security guard service.',
    availability: 'Immediate',
    gpsLat: -17.778,
    gpsLng: 31.055,
    featured: true,
    views: 910,
    createdAt: Date.now() - 10 * 86400000,
    updatedAt: Date.now() - 1 * 86400000,
  },
  {
    id: 'prop_byo_hillside_house',
    landlordId: 'user_manager_1',
    landlordName: 'Farai Ncube (Premier Estates)',
    landlordPhone: '+263 78 345 6789',
    name: 'Spacious 3-Bed Family Home with Swimming Pool & Borehole',
    propertyType: 'House',
    rentUsd: 650,
    rentZig: 17875,
    depositUsd: 650,
    province: 'Bulawayo',
    city: 'Bulawayo',
    suburb: 'Hillside',
    address: 'Cecil Avenue, Hillside, Bulawayo',
    bedrooms: 3,
    bathrooms: 2,
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
    ],
    amenities: [
      'Borehole Water',
      'Solar Power',
      'Parking',
      'Pet Friendly',
      'Walled & Gated',
      '24/7 Security',
      'Water Tank',
    ],
    description:
      'Immaculate family residence in prime Hillside, Bulawayo. Complete with sparkling pool, lush garden fed by reliable borehole, 8kVA solar system with lithium batteries, double lockup garage, electric fence, and staff quarters.',
    availability: 'Next Month',
    gpsLat: -20.185,
    gpsLng: 28.601,
    featured: false,
    views: 415,
    createdAt: Date.now() - 25 * 86400000,
    updatedAt: Date.now() - 4 * 86400000,
  },
  {
    id: 'prop_gweru_daylesford_cottage',
    landlordId: 'user_landlord_1',
    landlordName: 'Tendai Mutasa',
    landlordPhone: '+263 77 212 3456',
    name: 'Cozy 1-Bed Cottage Near MSU Main Campus',
    propertyType: 'Cottage',
    rentUsd: 150,
    rentZig: 4125,
    depositUsd: 100,
    province: 'Midlands',
    city: 'Gweru',
    suburb: 'Daylesford',
    address: 'MSU Drive / Daylesford, Gweru',
    bedrooms: 1,
    bathrooms: 1,
    photos: [
      'https://images.unsplash.com/photo-1502005229762-ee1b40280b8e?w=800&auto=format&fit=crop&q=80',
    ],
    amenities: [
      'Solar Power',
      'Borehole Water',
      'Prepaid ZESA',
      'WiFi',
      'Walled & Gated',
    ],
    description:
      'Quiet and secure cottage ideal for Midlands State University (MSU) lecturers or post-grad students. Clean borehole water, solar lighting during load shedding, and secure parking.',
    availability: 'Immediate',
    gpsLat: -19.458,
    gpsLng: 29.818,
    featured: false,
    views: 280,
    createdAt: Date.now() - 18 * 86400000,
    updatedAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'prop_mutare_florida_house',
    landlordId: 'user_manager_1',
    landlordName: 'Farai Ncube (Premier Estates)',
    landlordPhone: '+263 78 345 6789',
    name: 'Scenic 2-Bed House in Florida, Mutare',
    propertyType: 'House',
    rentUsd: 320,
    rentZig: 8800,
    depositUsd: 320,
    province: 'Manicaland',
    city: 'Mutare',
    suburb: 'Florida',
    address: 'Aerodrome Road, Florida, Mutare',
    bedrooms: 2,
    bathrooms: 1,
    photos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80',
    ],
    amenities: [
      'Municipal Water Tank',
      'Prepaid ZESA',
      'Parking',
      'Pet Friendly',
      'Walled & Gated',
    ],
    description:
      'Picturesque home with mountain views in quiet Florida suburb. Neat garden, paved driveway, large veranda, and excellent proximity to Mutare CBD and schools.',
    availability: 'Immediate',
    gpsLat: -18.972,
    gpsLng: 32.653,
    featured: false,
    views: 195,
    createdAt: Date.now() - 12 * 86400000,
    updatedAt: Date.now() - 6 * 86400000,
  },
  {
    id: 'prop_vicfalls_mkhosana_flat',
    landlordId: 'user_manager_1',
    landlordName: 'Farai Ncube (Premier Estates)',
    landlordPhone: '+263 78 345 6789',
    name: 'Modern 1-Bed Tourism Staff Flat in Mkhosana',
    propertyType: 'Flat',
    rentUsd: 220,
    rentZig: 6050,
    depositUsd: 220,
    province: 'Matabeleland North',
    city: 'Victoria Falls',
    suburb: 'Mkhosana',
    address: 'Pelandaba Way, Mkhosana, Vic Falls',
    bedrooms: 1,
    bathrooms: 1,
    photos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&auto=format&fit=crop&q=80',
    ],
    amenities: [
      'Solar Power',
      'Water Tank',
      'Prepaid ZESA',
      'WiFi',
      'Walled & Gated',
    ],
    description:
      'Clean modern apartment tailored for tourism & hospitality staff in Victoria Falls. Reliable solar power, constant pressurized water, ceiling fans, and tiled floors.',
    availability: 'Immediate',
    gpsLat: -17.932,
    gpsLng: 25.828,
    featured: false,
    views: 310,
    createdAt: Date.now() - 8 * 86400000,
    updatedAt: Date.now() - 2 * 86400000,
  },
];

export const SEED_ROOMMATES: RoommateProfile[] = [
  {
    id: 'roommate_1',
    userId: 'user_tenant_1',
    name: 'Ruvimbo Chitepo',
    age: 24,
    gender: 'Female',
    occupation: 'Junior Software Engineer',
    budgetUsd: 140,
    studentStatus: 'Working Professional',
    universityOrWorkplace: 'Fintech Hub, Harare CBD',
    preferredProvinces: ['Harare'],
    preferredCities: ['Harare'],
    preferredSuburbs: ['Avenues', 'Avondale', 'Belvedere', 'Eastlea'],
    accommodationTypeWanted: ['Apartment', 'Flat', 'Cottage'],
    moveInDate: '2026-10-01',
    cleanliness: 'Very Clean',
    sleepSchedule: 'Early Bird',
    smokingPreference: 'Non-Smoker',
    drinkingPreference: 'Non-Drinker',
    guestPolicy: 'Occasional',
    petTolerance: 'Loves Pets',
    bio: 'Hi! I work in tech and work partly from home. Looking for a respectful, quiet female roommate to split a 2-bedroom flat in Avenues or Avondale. I love cooking and keeping common spaces spotless!',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+263 71 987 6543',
    email: 'ruvimbo.chitepo@gmail.com',
    verified: true,
    createdAt: Date.now() - 15 * 86400000,
  },
  {
    id: 'roommate_2',
    userId: 'user_student_kuda',
    name: 'Kudakwashe Moyo',
    age: 22,
    gender: 'Male',
    occupation: 'Accounting Student (Final Year)',
    budgetUsd: 90,
    studentStatus: 'Student',
    universityOrWorkplace: 'University of Zimbabwe (UZ)',
    preferredProvinces: ['Harare'],
    preferredCities: ['Harare'],
    preferredSuburbs: ['Mount Pleasant', 'Avondale', 'Vainona'],
    accommodationTypeWanted: ['Shared Room', 'Room', 'Student Accommodation'],
    moveInDate: '2026-10-15',
    cleanliness: 'Moderate',
    sleepSchedule: 'Night Owl',
    smokingPreference: 'Non-Smoker',
    drinkingPreference: 'Social Drinker',
    guestPolicy: 'Weekends Only',
    petTolerance: 'Neutral',
    bio: 'Fourth year accounting student at UZ. Easygoing, focused on exams, into soccer and chess. Looking for a neat male roommate to share rent near UZ.',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    phone: '+263 77 456 7890',
    email: 'kuda.moyo@student.uz.ac.zw',
    verified: true,
    createdAt: Date.now() - 20 * 86400000,
  },
  {
    id: 'roommate_3',
    userId: 'user_prof_tariro',
    name: 'Tariro Sithole',
    age: 27,
    gender: 'Female',
    occupation: 'Pharmacist',
    budgetUsd: 190,
    studentStatus: 'Working Professional',
    universityOrWorkplace: 'Parirenyatwa Hospital Area',
    preferredProvinces: ['Harare'],
    preferredCities: ['Harare'],
    preferredSuburbs: ['Belvedere', 'Milton Park', 'Avondale', 'Avenues'],
    accommodationTypeWanted: ['Apartment', 'Cottage', 'House'],
    moveInDate: '2026-10-01',
    cleanliness: 'Very Clean',
    sleepSchedule: 'Flexible',
    smokingPreference: 'Non-Smoker',
    drinkingPreference: 'Social Drinker',
    guestPolicy: 'Occasional',
    petTolerance: 'Loves Pets',
    bio: 'Hospital pharmacist with shifts. Non-intrusive, polite, and tidy. Looking for another professional female to find a clean 2-bedroom place with solar power & borehole.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    phone: '+263 78 889 0123',
    email: 'tariro.s@pharmacy.zw',
    verified: true,
    createdAt: Date.now() - 5 * 86400000,
  },
  {
    id: 'roommate_4',
    userId: 'user_byo_sipho',
    name: 'Sipho Dube',
    age: 25,
    gender: 'Male',
    occupation: 'Civil Engineer (NUST Alum)',
    budgetUsd: 130,
    studentStatus: 'Working Professional',
    universityOrWorkplace: 'Bulawayo City Infrastructure',
    preferredProvinces: ['Bulawayo'],
    preferredCities: ['Bulawayo'],
    preferredSuburbs: ['Bradfield', 'Hillside', 'Kumalo', 'Suburbs'],
    accommodationTypeWanted: ['Cottage', 'Apartment', 'Flat'],
    moveInDate: '2026-11-01',
    cleanliness: 'Very Clean',
    sleepSchedule: 'Early Bird',
    smokingPreference: 'Non-Smoker',
    drinkingPreference: 'Social Drinker',
    guestPolicy: 'Occasional',
    petTolerance: 'Neutral',
    bio: 'Working on civil projects in Bulawayo. Quiet, reliable on bills, non-smoker. Looking to team up with a fellow professional.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    phone: '+263 77 654 3210',
    email: 'sipho.dube@eng.byo.zw',
    verified: true,
    createdAt: Date.now() - 10 * 86400000,
  },
];

export const SEED_TENANTS: Tenant[] = [
  {
    id: 'tenant_1',
    landlordId: 'user_landlord_1',
    propertyId: 'prop_harare_avondale_cottage',
    propertyName: 'Modern 2-Bed Cottage with Solar & Borehole',
    unitNumber: 'Cottage B',
    name: 'Tatenda Madziva',
    phone: '+263 77 345 6789',
    email: 'tatenda.m@gmail.com',
    moveInDate: '2026-01-15',
    depositPaid: 380,
    rentAmount: 380,
    currency: 'USD',
    leaseEnd: '2027-01-14',
    emergencyContactName: 'Grace Madziva (Sister)',
    emergencyContactPhone: '+263 71 223 3445',
    status: 'active',
    notes: 'Consistently pays via EcoCash USD on 1st of every month. Excellent tenant.',
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: 'tenant_2',
    landlordId: 'user_landlord_1',
    propertyId: 'prop_harare_avenues_flat',
    propertyName: 'Renovated 1-Bed Avenues Apartment',
    unitNumber: 'Flat 4B',
    name: 'Blessing Ndlovu',
    phone: '+263 78 555 4321',
    email: 'blessing.n@yahoo.com',
    moveInDate: '2026-03-01',
    depositPaid: 260,
    rentAmount: 260,
    currency: 'USD',
    leaseEnd: '2027-02-28',
    emergencyContactName: 'Musa Ndlovu (Uncle)',
    emergencyContactPhone: '+263 77 999 8888',
    status: 'active',
    notes: 'Pays cash USD directly. Clean and quiet.',
    createdAt: Date.now() - 60 * 86400000,
  },
];

export const SEED_PAYMENTS: RentPayment[] = [
  {
    id: 'pay_1',
    propertyId: 'prop_harare_avondale_cottage',
    propertyName: 'Modern 2-Bed Cottage with Solar & Borehole',
    tenantId: 'tenant_1',
    tenantName: 'Tatenda Madziva',
    landlordId: 'user_landlord_1',
    amount: 380,
    currency: 'USD',
    dueDate: '2026-09-01',
    paymentDate: '2026-09-01',
    status: 'paid',
    paymentMethod: 'EcoCash',
    reference: 'EC-USD-8834921',
    receiptNumber: 'REC-2026-09-001',
    notes: 'September rent received in full via EcoCash USD wallet.',
    createdAt: Date.now() - 23 * 86400000,
  },
  {
    id: 'pay_2',
    propertyId: 'prop_harare_avenues_flat',
    propertyName: 'Renovated 1-Bed Avenues Apartment',
    tenantId: 'tenant_2',
    tenantName: 'Blessing Ndlovu',
    landlordId: 'user_landlord_1',
    amount: 260,
    currency: 'USD',
    dueDate: '2026-09-01',
    paymentDate: '2026-09-03',
    status: 'paid',
    paymentMethod: 'Cash (USD)',
    reference: 'CASH-HARARE-992',
    receiptNumber: 'REC-2026-09-002',
    notes: 'Cash handed in office. Receipt issued.',
    createdAt: Date.now() - 21 * 86400000,
  },
  {
    id: 'pay_3',
    propertyId: 'prop_harare_avondale_cottage',
    propertyName: 'Modern 2-Bed Cottage with Solar & Borehole',
    tenantId: 'tenant_1',
    tenantName: 'Tatenda Madziva',
    landlordId: 'user_landlord_1',
    amount: 380,
    currency: 'USD',
    dueDate: '2026-10-01',
    status: 'pending',
    notes: 'October 2026 rent schedule generated.',
    createdAt: Date.now() - 2 * 86400000,
  },
];

export const SEED_LEASES: Lease[] = [
  {
    id: 'lease_1',
    propertyId: 'prop_harare_avondale_cottage',
    propertyName: 'Modern 2-Bed Cottage with Solar & Borehole',
    tenantId: 'tenant_1',
    tenantName: 'Tatenda Madziva',
    landlordId: 'user_landlord_1',
    unitNumber: 'Cottage B',
    startDate: '2026-01-15',
    endDate: '2027-01-14',
    monthlyRent: 380,
    deposit: 380,
    terms: '12 months fixed residential lease. Rent payable on or before 1st of calendar month. Solar system inverter maintained by landlord. Water borehole shared with main house.',
    renewalDate: '2026-12-01',
    status: 'active',
    documentNotes: 'Signed physical lease copy archived in office cabinet #3.',
    createdAt: Date.now() - 90 * 86400000,
  },
  {
    id: 'lease_2',
    propertyId: 'prop_harare_avenues_flat',
    propertyName: 'Renovated 1-Bed Avenues Apartment',
    tenantId: 'tenant_2',
    tenantName: 'Blessing Ndlovu',
    landlordId: 'user_landlord_1',
    unitNumber: 'Flat 4B',
    startDate: '2026-03-01',
    endDate: '2027-02-28',
    monthlyRent: 260,
    deposit: 260,
    terms: 'Includes block security levy and borehole booster maintenance. No loud music after 10PM.',
    renewalDate: '2027-01-15',
    status: 'active',
    documentNotes: 'Digital copy scanned and stored locally.',
    createdAt: Date.now() - 60 * 86400000,
  },
];

export const SEED_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: 'maint_1',
    propertyId: 'prop_harare_avondale_cottage',
    propertyName: 'Modern 2-Bed Cottage with Solar & Borehole',
    tenantId: 'tenant_1',
    tenantName: 'Tatenda Madziva',
    landlordId: 'user_landlord_1',
    category: 'Solar / Power',
    title: 'Inverter changeover switch clicking during ZESA power cut',
    description: 'When ZESA goes off at 6pm, the inverter trips the cottage sub-board for 10 seconds before picking up. Would appreciate an electrician check.',
    urgency: 'medium',
    status: 'in_progress',
    photos: [],
    reportedAt: Date.now() - 3 * 86400000,
    estimatedCost: 35,
    assignedTo: 'Munyaradzi (Solar Tech)',
  },
  {
    id: 'maint_2',
    propertyId: 'prop_harare_avenues_flat',
    propertyName: 'Renovated 1-Bed Avenues Apartment',
    tenantId: 'tenant_2',
    tenantName: 'Blessing Ndlovu',
    landlordId: 'user_landlord_1',
    category: 'Plumbing',
    title: 'Kitchen sink tap leaking around washer',
    description: 'Slight drip under the kitchen mixer tap. Washer probably worn.',
    urgency: 'low',
    status: 'resolved',
    photos: [],
    reportedAt: Date.now() - 10 * 86400000,
    resolvedAt: Date.now() - 8 * 86400000,
    estimatedCost: 15,
    assignedTo: 'Plumber John',
  },
];

export const SEED_APPLICATIONS: RentalApplication[] = [
  {
    id: 'app_1',
    propertyId: 'prop_harare_avondale_cottage',
    propertyName: 'Modern 2-Bed Cottage with Solar & Borehole',
    landlordId: 'user_landlord_1',
    applicantId: 'user_tenant_1',
    applicantName: 'Ruvimbo Chitepo',
    applicantPhone: '+263 71 987 6543',
    applicantEmail: 'ruvimbo.chitepo@gmail.com',
    proposedMoveInDate: '2026-10-15',
    occupantsCount: 1,
    employmentStatus: 'Employed Full-Time (Software Engineer)',
    monthlyIncomeUsd: 1100,
    message: 'Hello Mr. Mutasa, I am very keen on the Avondale cottage. The solar backup and borehole water are ideal for my remote tech work. Ready to pay deposit + first month immediately.',
    status: 'pending',
    appliedAt: Date.now() - 1 * 86400000,
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_welcome',
    userId: 'user_tenant_1',
    title: 'Welcome to Comfort Housing Hub',
    message: 'Your offline-first housing, rental & roommate hub is ready. You can browse, apply, and manage rentals even without an internet connection.',
    type: 'message',
    read: false,
    timestamp: Date.now() - 1 * 3600000,
  },
  {
    id: 'notif_roommate_match',
    userId: 'user_tenant_1',
    title: 'New High Roommate Match (92%)',
    message: 'Tariro Sithole matched your budget ($140-$190) and preferred area (Avondale/Avenues) with non-smoker alignment.',
    type: 'roommate_match',
    read: false,
    timestamp: Date.now() - 4 * 3600000,
  },
  {
    id: 'notif_rent_schedule',
    userId: 'user_landlord_1',
    title: 'October Rent Due Soon',
    message: 'Rent reminders scheduled for 2 tenants in Avondale & Avenues for October 1st.',
    type: 'rent_due',
    read: false,
    timestamp: Date.now() - 12 * 3600000,
  },
];
